"""
Candidate Training Dataset Generator with Hard Negative Mining.
Builds balanced pairwise training data from candidate blocking and ground truth.
"""

import os
import gc
import json
import time
import random
from typing import Dict, List, Tuple, Set, Any
import numpy as np
import pandas as pd

try:
    from .blocking import CandidateBlocker
    from .normalize import normalize_business_name, normalize_business_address
except ImportError:
    from blocking import CandidateBlocker
    from normalize import normalize_business_name, normalize_business_address


def generate_training_pairs(
    train_s1_path: str = "dataset/train/train_source1.tsv",
    train_s2_path: str = "dataset/train/train_source2.tsv",
    train_s3_path: str = "dataset/train/train_source3.tsv",
    train_gt_path: str = "dataset/train/train_ground_truth.tsv",
    val_s1_ids_path: str = "data/validation/val_s1_ids.json",
    sample_s1_count: int = 40000,
    neg_to_pos_ratio: int = 8,
    seed: int = 42,
) -> Tuple[List[Tuple[str, str]], List[int], Dict[str, Any], Dict[str, Any]]:
    """
    Generate labeled pairwise training dataset:
      - Excludes validation S1 entities to guarantee zero data leakage.
      - Positives: True matches from ground truth.
      - Negatives: Hard negatives generated by candidate blocker that do not match ground truth.
    
    Returns:
      pairs: List of (s1_id, target_id)
      labels: List of binary int labels (1 for match, 0 for non-match)
      s1_meta_dict: s1_id -> (name_meta, addr_meta)
      target_meta_dict: target_id -> (name_meta, addr_meta)
    """
    random.seed(seed)
    np.random.seed(seed)
    print(f"Generating training candidate pairs (sample_s1={sample_s1_count:,}, ratio={neg_to_pos_ratio}:1)...")
    t0 = time.time()

    # 1. Load validation IDs to exclude
    with open(val_s1_ids_path) as f:
        val_s1_ids = set(json.load(f))
    print(f"Excluding {len(val_s1_ids):,} validation S1 entities from training pool.")

    # 2. Load ground truth
    print("Loading ground truth...")
    gt_df = pd.read_csv(train_gt_path, sep="\t", dtype=str)
    gt_dict = {}
    for s1, m in zip(gt_df["source1_entity_id"], gt_df["matched_entity_ids"].fillna("")):
        if s1 in val_s1_ids:
            continue
        gt_dict[s1] = set(x.strip() for x in m.split(",") if x.strip())
    del gt_df
    gc.collect()

    # 3. Sample training S1 entities (excluding validation)
    print("Loading and sampling training S1 entities...")
    s1_df = pd.read_csv(train_s1_path, sep="\t", dtype=str)
    train_pool = s1_df[~s1_df["entity_id"].isin(val_s1_ids)].copy()
    del s1_df
    gc.collect()

    # Sample S1 entities proportionally by country
    sampled_s1 = train_pool.sample(n=min(sample_s1_count, len(train_pool)), random_state=seed)
    sampled_s1_ids = set(sampled_s1["entity_id"])
    del train_pool
    gc.collect()

    # Precompute S1 metadata
    s1_meta_dict = {}
    for row in sampled_s1.itertuples(index=False):
        n_meta = normalize_business_name(row.business_name)
        a_meta = normalize_business_address(row.business_address)
        s1_meta_dict[row.entity_id] = (n_meta, a_meta)

    # Collect true positive pairs
    positive_pairs = []
    needed_target_ids = set()
    for s1_id in sampled_s1_ids:
        true_targets = gt_dict.get(s1_id, set())
        for tid in true_targets:
            positive_pairs.append((s1_id, tid))
            needed_target_ids.add(tid)

    print(f"Collected {len(positive_pairs):,} true positive pairs across sampled S1.")

    # 4. Generate hard negatives using Candidate Blocker per country
    print("Generating hard negative candidates using blocker...")
    blocker = CandidateBlocker(max_token_freq=15000, max_candidates_per_s1=60)

    # Process country partitions (India and US)
    hard_negative_pairs = []
    for country in ["India", "US"]:
        c_s1 = sampled_s1[sampled_s1["country"] == country]
        if len(c_s1) == 0:
            continue
        print(f"  Indexing target records for {country}...")
        s2_chunks = [c[c["country"] == country] for c in pd.read_csv(train_s2_path, sep="\t", dtype=str, chunksize=500000)]
        s3_chunks = [c[c["country"] == country] for c in pd.read_csv(train_s3_path, sep="\t", dtype=str, chunksize=500000)]
        targets_c = pd.concat(s2_chunks + s3_chunks, ignore_index=True)
        del s2_chunks, s3_chunks
        gc.collect()

        # Build index
        country_blocker = CandidateBlocker(max_token_freq=15000, max_candidates_per_s1=60)
        country_blocker.index_target_records(targets_c)

        # Index metadata for needed targets
        print(f"  Querying candidates for {len(c_s1):,} {country} S1 records...")
        for row in c_s1.itertuples(index=False):
            s1_id = row.entity_id
            true_set = gt_dict.get(s1_id, set())
            cands = country_blocker.generate_candidates_for_s1(row.business_name, row.business_address)
            
            # Negatives are candidates not in true set
            negs = list(cands - true_set)
            # Subsample negatives per S1
            n_sample_neg = max(1, min(len(negs), len(true_set) * neg_to_pos_ratio if true_set else 2))
            if negs:
                sampled_negs = random.sample(negs, min(len(negs), n_sample_neg))
                for tid in sampled_negs:
                    hard_negative_pairs.append((s1_id, tid))
                    needed_target_ids.add(tid)

        del targets_c, country_blocker
        gc.collect()

    print(f"Collected {len(hard_negative_pairs):,} hard negative pairs.")

    # 5. Load metadata for all needed target IDs (positives + hard negatives)
    print(f"Loading metadata for {len(needed_target_ids):,} unique target entities...")
    target_meta_dict = {}
    for path in [train_s2_path, train_s3_path]:
        for chunk in pd.read_csv(path, sep="\t", dtype=str, chunksize=500000):
            hit = chunk[chunk["entity_id"].isin(needed_target_ids)]
            for row in hit.itertuples(index=False):
                if row.entity_id not in target_meta_dict:
                    n_meta = normalize_business_name(row.business_name)
                    a_meta = normalize_business_address(row.business_address)
                    target_meta_dict[row.entity_id] = (n_meta, a_meta)
            if len(target_meta_dict) == len(needed_target_ids):
                break
        gc.collect()

    # Filter pairs where target metadata was resolved
    valid_pos = [(s1, tid) for s1, tid in positive_pairs if tid in target_meta_dict]
    valid_neg = [(s1, tid) for s1, tid in hard_negative_pairs if tid in target_meta_dict]

    # Combine and shuffle
    all_pairs = valid_pos + valid_neg
    all_labels = [1] * len(valid_pos) + [0] * len(valid_neg)

    combined = list(zip(all_pairs, all_labels))
    random.shuffle(combined)
    all_pairs = [p for p, _ in combined]
    all_labels = [lbl for _, lbl in combined]

    elapsed = round(time.time() - t0, 1)
    print(f"\nTraining Dataset Ready in {elapsed}s:")
    print(f"  Total Pairs:    {len(all_pairs):,}")
    print(f"  Positive (1):   {len(valid_pos):,} ({round(100*len(valid_pos)/len(all_pairs), 1)}%)")
    print(f"  Negative (0):   {len(valid_neg):,} ({round(100*len(valid_neg)/len(all_pairs), 1)}%)")

    return all_pairs, all_labels, s1_meta_dict, target_meta_dict
